window.VSB_CONFIG = {
  SUPABASE_URL: "PASTE_SUPABASE_PROJECT_URL_HERE",
  SUPABASE_ANON_KEY: "PASTE_SUPABASE_ANON_KEY_HERE",
  ADMIN_EMAILS: ["your-admin-email@example.com"],
  OTP_ENDPOINT: "/otp.php",
};
